name: docs

on:
  push:
    branches: [main]
  workflow_dispatch:  # 手動トリガ

permissions:
  contents: write  # gh-deploy が gh-pages ブランチへ push する権限

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docs deps
        run: |
          pip install mkdocs-material mkdocstrings[python]

      - name: Install project (editable)
        run: |
          pip install -e .

      - name: Build & deploy
        run: |
          mkdocs gh-deploy --force --clean --verbose