name: Publish to Test PyPI

on:
  push:
    tags:
      - "v*.*.*"    # v0.1.0 みたいなタグPushをトリガーにする
  workflow_dispatch:  # 手動トリガ

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Publish to TestPyPI
        env:
          POETRY_HTTP_BASIC_TEST_PYPI_USERNAME: __token__
          POETRY_HTTP_BASIC_TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: poetry publish -r test-pypi --skip-existing --build --no-interaction